<HomeButton@Button>:
	font_size: '30'
    #color: (.6, .6, .6, 1)
	size_hint: 1, 1
	background_normal:'./images/DNA.png'
	background_down:'./images/DNA_press.png'
	
ShowcaseScreen:
    name: 'Home'
    fullscreen: True

    GridLayout:
		cols:3
		padding:50
		spacing:30
		size: root.width, root.height
		
		HomeButton:
			
			
			on_release:app.go_screen('DNA')
			
			
				
		HomeButton:
			

		HomeButton:
			
			
		HomeButton:
			
		
		HomeButton:
			
			
		HomeButton:
					
		