ShowcaseScreen:
    name: 'DNA Broad Range'
    #fullscreen: True
	
	BoxLayout:
		orientation: "vertical"
		padding:50
		spacing:30
		
		Label:
			text:'Enter original sample volume'
			font_size:36
			size_hint:(1,0.2)
			
		Label:
			id:brightness_value
			text:'{}'.format(bright.value)
			font_size:36
			size_hint:(1,0.2)	
			
		Slider:
			min:50
			max:255
			step:1
			id: bright
			orientation: 'horizontal'
			value:int(app.brightness)
			on_value:
			
		Label:
			id:brightness_value
			text:'Output sample units'
			font_size:36
			size_hint:(1,0.2)
		
		Spinner:
			id:s_dna_units
			text: 'ng/μL'
			values: ('ng/μL', 'ng/ML', 'μg/μL', 'μg/mL', 'mg/mL')
			#size_hint_y: None
			on_text: 
				if s_contrast.text == "BT.709-2": root.spinner_contrast(0)
				elif s_contrast.text == "BT.709-1": root.spinner_contrast(1)
				elif s_contrast.text == "BT.709": root.spinner_contrast(2)
				elif s_contrast.text == "BT.709+1": root.spinner_contrast(3)
				elif s_contrast.text == "BT.709+2": root.spinner_contrast(4)
			