ShowcaseScreen:
    name: 'DNA Result'
    fullscreen: True
	BoxLayout:
		orientation: "vertical"
		padding:60
		spacing:20
		BoxLayout:	
			orientation: "vertical"
			size_hint:1,0.8
			Label:
				text:"Result"
				font_size:36
				color: '#c40e25'
			Label:
				id:DNA_result
				#text:'{}'.format(app.DNA_result)
				text:app.DNA_result
				font_size:36
				color: '#c40e25'
				
			Label:
				id:DNA_result_real
				text:app.DNA_result_real
				font_size:48
				color: '#c40e25'	
				
		BoxLayout:	
			size_hint:1,0.2
			spacing:40
			orientation: "horizontal"
			
			Button:
				text:"Read tube"
				font_size:30
				background_normal: ''
				background_color: '#c40e25'
				on_release:
					app.read_AccuClear_tube() if app.DNA_type == 'AccuClear' else \ 
					app.read_AccuGreen_tube()