ShowcaseScreen:
    name: 'DNA'
    fullscreen: True
	BoxLayout:
		orientation: "vertical"
		padding:60
		spacing:60
		
		Button:
			text:"Read Sample"
			font_size:30
			background_normal: ''
			background_color: '#c40e25'
			on_release: app.go_screen('DNA Broad Range')
		Button:
			text:"Read Standard"
			font_size:30
			background_normal: ''
			background_color: '#c40e25'
			on_release: app.go_screen('Read Standard')
		Label:
			text:"Last read standards"
			color:0, 0, 0, 1 
			font_size:20	
			
		
		