ShowcaseScreen:
    name: 'Read DNA'
    fullscreen: True
	BoxLayout:
		size_hint:(1, 0.9)
		orientation: "vertical"
		padding:60
		spacing:60
		
		Label:
			id:DNA_type
			text:app.DNA_type
			color: '#c40e25'
			font_size:48
			
		Button:
			text:"Read Sample"
			font_size:30
			background_normal: ''
			background_color: '#c40e25'
			on_release: app.go_screen('DNA Broad Range')
		Button:
			text:"Read Standard"
			font_size:30
			background_normal: ''
			background_color: '#c40e25'
			on_release: app.go_screen('Read Standard')
			
		Label:
			text:"Last read standards"
			color: '#c40e25'
			font_size:20	
			
	BoxLayout:
		size_hint:(1, 0.1)
		orientation: "horizontal"	
		Label:
			id:DNA_type
			text:app.DNA_type
			color: '#c40e25'
			font_size:20
		Label:
			color: '#c40e25'
			font_size:20	
			text:app.DNA_last_read_1
		Label:
			color: '#c40e25'
			font_size:20	
			text:app.DNA_last_read_2	
		