ShowcaseScreen:
    name: 'DNA Standard'
    fullscreen: True
	BoxLayout:
		orientation: "vertical"
		padding:60
		spacing:20
		BoxLayout:	
			size_hint:1,0.8
			Label:
				text:"Please insert standard 1"
				font_size:36	
			
		BoxLayout:	
			size_hint:1,0.2
			spacing:40
			orientation: "horizontal"
			Button:
				text:"Cancel"
				font_size:30
				on_release:app.go_previous()
				
			Button:
				text:"Read Standard 1"
				font_size:30
				on_release:app.read_standard_1()
			
		
		